/**
 * Design tokens — auto-generated by scripts/sync-tokens.js
 * Source: Stitch design system assets/3768688388941177004
 * Last sync: 2026-04-13T13:40:09.558Z
 *
 * DO NOT EDIT MANUALLY — run `npm run tokens:sync` to update.
 */

export const color = {
  primary: 'var(--color-primary)',
  primaryContainer: 'var(--color-primary-container)',
  onPrimary: 'var(--color-on-primary)',
  onPrimaryContainer: 'var(--color-on-primary-container)',
  primaryFixed: 'var(--color-primary-fixed)',
  primaryFixedDim: 'var(--color-primary-fixed-dim)',
  onPrimaryFixed: 'var(--color-on-primary-fixed)',
  onPrimaryFixedVariant: 'var(--color-on-primary-fixed-variant)',
  inversePrimary: 'var(--color-inverse-primary)',
  secondary: 'var(--color-secondary)',
  onSecondary: 'var(--color-on-secondary)',
  secondaryContainer: 'var(--color-secondary-container)',
  onSecondaryContainer: 'var(--color-on-secondary-container)',
  secondaryFixed: 'var(--color-secondary-fixed)',
  secondaryFixedDim: 'var(--color-secondary-fixed-dim)',
  onSecondaryFixed: 'var(--color-on-secondary-fixed)',
  onSecondaryFixedVariant: 'var(--color-on-secondary-fixed-variant)',
  tertiary: 'var(--color-tertiary)',
  onTertiary: 'var(--color-on-tertiary)',
  tertiaryContainer: 'var(--color-tertiary-container)',
  onTertiaryContainer: 'var(--color-on-tertiary-container)',
  tertiaryFixed: 'var(--color-tertiary-fixed)',
  tertiaryFixedDim: 'var(--color-tertiary-fixed-dim)',
  onTertiaryFixed: 'var(--color-on-tertiary-fixed)',
  onTertiaryFixedVariant: 'var(--color-on-tertiary-fixed-variant)',
  surface: 'var(--color-surface)',
  surfaceDim: 'var(--color-surface-dim)',
  surfaceBright: 'var(--color-surface-bright)',
  surfaceContainerLowest: 'var(--color-surface-container-lowest)',
  surfaceContainerLow: 'var(--color-surface-container-low)',
  surfaceContainer: 'var(--color-surface-container)',
  surfaceContainerHigh: 'var(--color-surface-container-high)',
  surfaceContainerHighest: 'var(--color-surface-container-highest)',
  surfaceVariant: 'var(--color-surface-variant)',
  surfaceTint: 'var(--color-surface-tint)',
  onSurface: 'var(--color-on-surface)',
  onSurfaceVariant: 'var(--color-on-surface-variant)',
  inverseSurface: 'var(--color-inverse-surface)',
  inverseOnSurface: 'var(--color-inverse-on-surface)',
  background: 'var(--color-background)',
  onBackground: 'var(--color-on-background)',
  outline: 'var(--color-outline)',
  outlineVariant: 'var(--color-outline-variant)',
  error: 'var(--color-error)',
  errorContainer: 'var(--color-error-container)',
  onError: 'var(--color-on-error)',
  onErrorContainer: 'var(--color-on-error-container)',
} as const

export const font = {
  headline: 'var(--font-headline)',
  body: 'var(--font-body)',
  label: 'var(--font-label)',
} as const

export const radius = {
  DEFAULT: 'var(--radius-DEFAULT)',
  sm: 'var(--radius-sm)',
  lg: 'var(--radius-lg)',
  xl: 'var(--radius-xl)',
  full: 'var(--radius-full)',
} as const

export const space = {
  xs: '0.25rem',
  sm: '0.5rem',
  md: '1rem',
  lg: '1.5rem',
  xl: '2rem',
  '2xl': '3rem',
} as const

export type ColorToken =
  | 'primary'
  | 'primaryContainer'
  | 'onPrimary'
  | 'onPrimaryContainer'
  | 'primaryFixed'
  | 'primaryFixedDim'
  | 'onPrimaryFixed'
  | 'onPrimaryFixedVariant'
  | 'inversePrimary'
  | 'secondary'
  | 'onSecondary'
  | 'secondaryContainer'
  | 'onSecondaryContainer'
  | 'secondaryFixed'
  | 'secondaryFixedDim'
  | 'onSecondaryFixed'
  | 'onSecondaryFixedVariant'
  | 'tertiary'
  | 'onTertiary'
  | 'tertiaryContainer'
  | 'onTertiaryContainer'
  | 'tertiaryFixed'
  | 'tertiaryFixedDim'
  | 'onTertiaryFixed'
  | 'onTertiaryFixedVariant'
  | 'surface'
  | 'surfaceDim'
  | 'surfaceBright'
  | 'surfaceContainerLowest'
  | 'surfaceContainerLow'
  | 'surfaceContainer'
  | 'surfaceContainerHigh'
  | 'surfaceContainerHighest'
  | 'surfaceVariant'
  | 'surfaceTint'
  | 'onSurface'
  | 'onSurfaceVariant'
  | 'inverseSurface'
  | 'inverseOnSurface'
  | 'background'
  | 'onBackground'
  | 'outline'
  | 'outlineVariant'
  | 'error'
  | 'errorContainer'
  | 'onError'
  | 'onErrorContainer'

export type FontToken = keyof typeof font
export type RadiusToken = keyof typeof radius
export type SpaceToken = keyof typeof space

export const tokens = { color, font, radius, space } as const
export type Tokens = typeof tokens
