#!/usr/bin/env node
/**
 * scripts/sync-tokens.js
 *
 * Syncs design tokens from the Stitch design system into:
 *   - app/styles/main.css  (CSS custom properties inside @theme)
 *   - app/utils/tokens.ts  (TypeScript constants)
 *
 * Usage:
 *   npm run tokens:sync
 *
 * Stitch project:  3441274017997193544
 * Design system:   assets/3768688388941177004
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')

// ── Stitch design system definition (source of truth) ─────────────────────────
// This mirrors the Stitch design system created via MCP.
// When Stitch exports tokens, map them here and re-run this script.
const STITCH_TOKENS = {
  meta: {
    projectId: '3441274017997193544',
    designSystemId: 'assets/3768688388941177004',
    displayName: 'E-Commerce Design System',
    lastSync: new Date().toISOString(),
  },

  colors: {
    // Primary
    primary: '#8a5100',
    'primary-container': '#ff9900',
    'on-primary': '#ffffff',
    'on-primary-container': '#653a00',
    'primary-fixed': '#ffdcbd',
    'primary-fixed-dim': '#ffb86f',
    'on-primary-fixed': '#2c1600',
    'on-primary-fixed-variant': '#693c00',
    'inverse-primary': '#ffb86f',

    // Secondary
    secondary: '#595f68',
    'on-secondary': '#ffffff',
    'secondary-container': '#dae0eb',
    'on-secondary-container': '#5d636d',
    'secondary-fixed': '#dde3ee',
    'secondary-fixed-dim': '#c1c7d2',
    'on-secondary-fixed': '#161c24',
    'on-secondary-fixed-variant': '#414750',

    // Tertiary
    tertiary: '#5e5e5e',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#b2b1b1',
    'on-tertiary-container': '#434444',
    'tertiary-fixed': '#e3e2e2',
    'tertiary-fixed-dim': '#c7c6c6',
    'on-tertiary-fixed': '#1b1c1c',
    'on-tertiary-fixed-variant': '#464747',

    // Surface
    surface: '#f9f9f9',
    'surface-dim': '#dadada',
    'surface-bright': '#f9f9f9',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#f3f3f3',
    'surface-container': '#eeeeee',
    'surface-container-high': '#e8e8e8',
    'surface-container-highest': '#e2e2e2',
    'surface-variant': '#e2e2e2',
    'surface-tint': '#8a5100',
    'on-surface': '#1a1c1c',
    'on-surface-variant': '#554434',
    'inverse-surface': '#2f3131',
    'inverse-on-surface': '#f1f1f1',

    // Background
    background: '#f9f9f9',
    'on-background': '#1a1c1c',

    // Outline
    outline: '#887361',
    'outline-variant': '#dbc2ad',

    // Error
    error: '#ba1a1a',
    'error-container': '#ffdad6',
    'on-error': '#ffffff',
    'on-error-container': '#93000a',
  },

  fonts: {
    headline: '"Work Sans", sans-serif',
    body: '"Plus Jakarta Sans", sans-serif',
    label: '"Plus Jakarta Sans", sans-serif',
  },

  radius: {
    DEFAULT: '0.25rem',
    sm: '0.125rem',
    lg: '0.375rem',
    xl: '0.5rem',
    full: '9999px',
  },

  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
  },
}

// ── Generate CSS ───────────────────────────────────────────────────────────────
function generateCSS(tokens) {
  const colorLines = Object.entries(tokens.colors)
    .map(([k, v]) => `  --color-${k}: ${v};`)
    .join('\n')

  const fontLines = Object.entries(tokens.fonts)
    .map(([k, v]) => `  --font-${k}: ${v};`)
    .join('\n')

  const radiusLines = Object.entries(tokens.radius)
    .map(([k, v]) => `  --radius-${k}: ${v};`)
    .join('\n')

  return `@import "tailwindcss";
@import "@nuxt/ui";

/* ── Design tokens (Tailwind v4 @theme — must stay in .css) ── */
/* Auto-generated by scripts/sync-tokens.js — DO NOT EDIT MANUALLY */
/* Last sync: ${tokens.meta.lastSync} */
@theme {
  /* Colors */
${colorLines}

  /* Fonts */
${fontLines}

  /* Border radius */
${radiusLines}
}
`
}

// ── Generate TypeScript ────────────────────────────────────────────────────────
function toCamelCase(str) {
  return str.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
}

function generateTS(tokens) {
  const colorEntries = Object.entries(tokens.colors)
    .map(([k]) => `  ${toCamelCase(k).padEnd(26)}: 'var(--color-${k})',`)
    .join('\n')

  const fontEntries = Object.entries(tokens.fonts)
    .map(([k]) => `  ${k.padEnd(8)}: 'var(--font-${k})',`)
    .join('\n')

  const radiusEntries = Object.entries(tokens.radius)
    .map(([k]) => `  ${k.padEnd(8)}: 'var(--radius-${k})',`)
    .join('\n')

  const spaceEntries = Object.entries(tokens.spacing)
    .map(([k, v]) => `  '${k}'${''.padEnd(Math.max(0, 4 - k.length))}: '${v}',`)
    .join('\n')

  const colorKeys = Object.keys(tokens.colors)
    .map((k) => `  | '${toCamelCase(k)}'`)
    .join('\n')

  return `/**
 * Design tokens — auto-generated by scripts/sync-tokens.js
 * Source: Stitch design system ${tokens.meta.designSystemId}
 * Last sync: ${tokens.meta.lastSync}
 *
 * DO NOT EDIT MANUALLY — run \`npm run tokens:sync\` to update.
 */

export const color = {
${colorEntries}
} as const

export const font = {
${fontEntries}
} as const

export const radius = {
${radiusEntries}
} as const

export const space = {
${spaceEntries}
} as const

export type ColorToken =
${colorKeys}

export type FontToken   = keyof typeof font
export type RadiusToken = keyof typeof radius
export type SpaceToken  = keyof typeof space

export const tokens = { color, font, radius, space } as const
export type Tokens = typeof tokens
`
}

// ── Diff check ─────────────────────────────────────────────────────────────────
function hasDrift(filePath, newContent) {
  if (!fs.existsSync(filePath)) return true
  const existing = fs.readFileSync(filePath, 'utf8')
  // Strip the timestamp line for comparison
  const strip = (s) => s.replace(/Last sync: .+/g, 'Last sync: __TS__')
  return strip(existing) !== strip(newContent)
}

// ── Main ───────────────────────────────────────────────────────────────────────
const cssPath = path.join(ROOT, 'app/styles/main.css')
const tsPath = path.join(ROOT, 'app/utils/tokens.ts')

const newCSS = generateCSS(STITCH_TOKENS)
const newTS = generateTS(STITCH_TOKENS)

const checkOnly = process.argv.includes('--check')

let driftFound = false

if (hasDrift(cssPath, newCSS)) {
  if (checkOnly) {
    console.error(
      '❌ Token drift detected in app/styles/main.css — run `npm run tokens:sync` to fix.'
    )
    driftFound = true
  } else {
    fs.writeFileSync(cssPath, newCSS)
    console.log('✅ app/styles/main.css updated')
  }
} else {
  console.log('✓  app/styles/main.css is in sync')
}

if (hasDrift(tsPath, newTS)) {
  if (checkOnly) {
    console.error(
      '❌ Token drift detected in app/utils/tokens.ts — run `npm run tokens:sync` to fix.'
    )
    driftFound = true
  } else {
    fs.writeFileSync(tsPath, newTS)
    console.log('✅ app/utils/tokens.ts updated')
  }
} else {
  console.log('✓  app/utils/tokens.ts is in sync')
}

if (driftFound) process.exit(1)
